version: '3.7'
services:
  server:
    build: ./services/server
    env_file: ./services/server/.env
    ports:
      - "3333:3333"
    volumes:
      - ./services/server:/usr/src/app
      - /usr/src/app/node_modules/
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    restart: always
    volumes:
      - ./dynamodb-data:/data
    ports:
      - "8000:8000"
  local-dev-s3:
    image: minio/minio
    volumes:
      - .minio/data:/export
    ports:
      - "9000:9000"
    env_file: ./services/server/.env
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3