version: '3.7'
services:
  server:
    build: ./services/server
    env_file: ./services/server/.env
    ports:
      - "3333:3333"
    volumes:
      - ./services/server:/usr/src/app
      - /usr/src/app/node_modules/
    depends_on:
     - dynamodb-local
     - authenticator
     - local-dev-s3
  dynamodb-local:
    image: amazon/dynamodb-local:latest
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath /data"
    restart: always
    volumes:
      - ./dynamodb-data:/data
    ports:
      - "8000:8000"
  local-dev-s3:
    image: minio/minio
    volumes:
      - .minio/data:/export
    ports:
      - "9000:9000"
    env_file: ./services/server/.env
    command: server /export
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
  authenticator:
    build: ./services/authenticator
    env_file: ./services/authenticator/.env
    ports:
      - "4000:4000"
    volumes:
      - ./services/authenticator:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
     - local-dev-s3
  web-client:
    build: ./services/web-client
    env_file: ./services/web-client/.env
    ports:
      - "3000:3000"
    volumes:
      - ./services/web-client:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - /usr/src/app/.serverless_nextjs
    depends_on:
      - server