service: gadolinium-authenticator
# app and org for use with dashboard.serverless.com
#app: your-app-name
#org: your-org-name

# You can pin your service to only deploy with a specific Serverless version
# Check out our docs for more details
frameworkVersion: "=2.8.0"

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: us-east-1

plugins:
  - serverless-webpack
  - serverless-offline

custom:
  webpack:
    webpackConfig: './webpack.config.js'
    includeModules: true
  serverless-offline:
    host: "0.0.0.0"
    httpPort: 4000
    noPrependStageInUrl: true

functions:
  create:
    handler: src/handler.create
    memorySize: 128
    events:
      - http:
          path: 'create'
          method: 'post'
  validate:
    handler: src/handler.validate
    memorySize: 128
    events:
      - http:
          path: 'validate'
          method: 'post'
